name: cicd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: abc-store-cluster
  GKE_ZONE: asia-southeast2
  DEPLOYMENT_NAME: payment-service
  IMAGE: dockmathu/paymentservice:${{ github.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/paymentservice:${{ github.sha }}

      -
         name: Kuberentes (k8s) cli - kubectl
         uses: actions-hub/kubectl@v1.21.2

      -
        name: connect to k8s
        uses: gcloud container clusters get-credentials abc-store-cluster --region asia-southeast2 --project golden-sandbox-343808


     
    

