name: cicd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CLUSTER_NAME: abc-store-cluster
  CLUSTER_ZONE: asia-southeast2
  DEPLOYMENT_NAME: payment-service
  IMAGE: dockmathu/paymentservice:${{ github.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/paymentservice:${{ github.sha }}

      - # Set up kustomize
         name: Set up Kustomize
         run: |-
            curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
            chmod u+x ./kustomize

        # Deploy the Docker image to the GKE cluster
        -
          name: Deploy
          run: |-
            ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
            ./kustomize build . | kubectl apply -f -
            kubectl rollout status deployment/$DEPLOYMENT_NAME
            kubectl get services -o wide



     
    

